name: Get SA Email
on: workflow_dispatch
jobs:
  show:
    runs-on: ubuntu-latest
    steps:
      - name: Show email
        env:
          JSON: ${{ secrets.GSC_SERVICE_ACCOUNT_JSON }}
        run: echo "$JSON" | jq -r .client_email
